### ISSUE TITLE
Mining Contest

### ISSUE THREAD

**Issue by VoChiDanh** [D-x-Z/bCore#1]
```[17:27:05 WARN]: [bCore] Task #10029 for bCore v2.5 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "p" is null
        at net.danh.Manager.PlayerData.getPlayerName(PlayerData.java:105) ~[?:?]
        at net.danh.Contest.Mining$1.run(Mining.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by VoChiDanh** [comment]
![image](https://user-images.githubusercontent.com/86956269/159244508-2693584f-d47b-4490-a146-00970e760ed7.png)
